version: "3.9"
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    networks:
      main_network:
        ipv4_address: ${WEAVIATE_IP}
    env_file:
      - stack.env
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      # Désactive les modules ou ne pas inclure text2vec-transformers
      ENABLE_MODULES: ""
      DISABLE_TELEMETRY: "true"
      DEFAULT_VECTORIZER_MODULE: "none"
      # Ne pas définir TRANSFORMERS_INFERENCE_API
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped

  doc-harvester:
    build: ./
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      main_network:
        ipv4_address: ${HARVESTER_IP}
      harvester_internet:
    env_file:
      - stack.env
    environment:
      WEAVIATE_HOST: ${WEAVIATE_HOST:-weaviate}
      WEAVIATE_PORT: ${WEAVIATE_PORT:-8080}
      WEAVIATE_GRPC_PORT: ${WEAVIATE_GRPC_PORT:-50051}
      EMBEDDER_URL: ${EMBEDDER_URL:-http://ollama:11434/api/embeddings}
      MODEL_NAME: ${MODEL_NAME:-nomic-embed-text}
      VERSION_CACHE_TTL: 60
    volumes:
      - ./cache:/cache
    restart: unless-stopped

volumes:
  weaviate_data:
networks:
  main_network:
    external: true
    name: ${MAIN_NETWORK_NAME}
  harvester_internet:
    driver: bridge
    internal: false
