version: "3.9"
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    networks:
      main_network:
        ipv4_address: ${WEAVIATE_IP}
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      # Désactive les modules ou ne pas inclure text2vec-transformers
      ENABLE_MODULES: ""
      DEFAULT_VECTORIZER_MODULE: "none"
      # Ne pas définir TRANSFORMERS_INFERENCE_API
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped

  doc-harvester:
    build: ./
    networks:
      main_network:
        ipv4_address: ${HARVESTER_IP}
    environment:
      WEAVIATE_URL: http://weaviate:8080
      EMBEDDER_URL: http://127.0.0.1:11434/api/embeddings
      MODEL_NAME: nomic-embed-text
    volumes:
      - ./cache:/cache
    restart: unless-stopped

volumes:
  weaviate_data:
networks:
  main_network:
    external: true
    name: ${MAIN_NETWORK_NAME}
