go:
  repo: "https://github.com/golang/go.git"
  path: "doc"

tinygo:
  repo: "https://github.com/tinygo-org/tinygo.git"
  path: "src/runtime"

php:
  repo: "https://github.com/php/doc-en.git"
  path: "en"

react:
  repo: "https://github.com/reactjs/react.dev.git"
  path: "src/content"
